[DEFAULT]
root.path=.
data.path=./data
output.path=./outputs
assets.path=./assets

[MAC]
root.path=.
data.path=./data
output.path=./outputs
assets.path=./assets

[GCP]
root.path=.
data.path=./data
output.path=./outputs
assets.path=./assets
